### ISSUE TITLE
Why this repository is not public? 

### ISSUE THREAD

**Issue by BulatSaif** [paritytech/chainspecs#11]
## Why this repository is not public?

1. This repository was created mostly for internal usage https://github.com/paritytech/devops/issues/1299
2. The repository is private, but GitHub pages is public because sometimes we need to allow partners to connect. But we don't want random nodes to connect to our internal test chains and spoil the tests.
3. we should have a single source of truth, and for public chains we already have it : binary (e.g `--chain kusama`)

There are no problems to make this repo open-source (we can remove private chainspec). We can open-source this repo if it will be useful for the community. Parity has a lot of open-source.

**Comment by PierreBesson** [comment]
The repo was just made public.
