### ISSUE TITLE
Publish to NPM?

### ISSUE THREAD

**Issue by jsdw** [paritytech/chainspecs#246]
Having a repo of chainspecs that is kept uptodate like this is super handy! 

We use chainspecs in JS land eg in https://github.com/paritytech/substrate-connect/tree/main/packages/connect-known-chains/specs, and so I'm wondering how feasible it would be to have some CI step publish this to NPM when specs update, so that we could point here rather than have any separate packages containing chain specs that need keeping uptodate?

**Comment by BulatSaif** [comment]
You can already point your application to these chainspecs, as they are available via HTTPS links: [https://paritytech.github.io/chainspecs/](https://paritytech.github.io/chainspecs/). We can create a meta file that contains a list of all specs in JSON format.

Chain specs used for substrate-connect are a bit different, as they are meant for light clients. After each sudo force finalize call, you have to create a new chainspec from that point in time. I'm not sure if you can even use this chainspec to sync a regular Substrate node. The chainspec in this repo is called genesis chainspecs, which allow you to sync from block 0.

Compare Kusama asset hub chainspec:
- [Substrate-connect Kusama Asset Hub chainspec](https://github.com/paritytech/substrate-connect/blob/main/packages/connect-known-chains/specs/ksmcc3_asset_hub.json)
- [Official Kusama Asset Hub chainspec](https://paritytech.github.io/chainspecs/kusama/parachain/asset-hub/chainspec.json)

There may also be legal issues. Posting a package on npm under our name that contains code from third-party developers without their approval can have legal consequences. We would need to check the license for each repo and monitor any changes in the license. Currently, this repo contains only links to external code, not the code itself.

**Comment by jsdw** [comment]
Thanks for the info! I keep forgetting that chainspecs differ from light client to full node, but yup that all makes sense!

I'll close this issue :)
